Repository guildedjs/guilded.js, pull requests merged in 2022-04, with the labels that each got.

#59 feat: client user
  packages/guilded-api-typings/lib/v1/ws/Events.ts
  packages/guilded.js/lib/structures/Client.ts
  packages/guilded.js/lib/structures/User.ts
  packages/ws/lib/WebSocketManager.ts
Labels: enhancement

#57 feat: member ban ws event handling
  packages/guilded-api-typings/lib/v1/ws/Events.ts
  packages/guilded.js/lib/constants.ts
  packages/guilded.js/lib/gateway/ClientGatewayHandler.ts
  packages/guilded.js/lib/gateway/handler/TeamMemberEventHandler.ts
  packages/guilded.js/lib/structures/Client.ts
  packages/guilded.js/lib/structures/Member.ts
Labels: enhancement

#22 feat: base of command framework
  package.json
  packages/framework/LICENSE
  packages/framework/README.md
  packages/framework/lib/BotClient.ts
  packages/framework/lib/arguments/...string.ts
  packages/framework/lib/arguments/boolean.ts
  packages/framework/lib/arguments/command.ts
  packages/framework/lib/arguments/duration.ts
  packages/framework/lib/arguments/number.ts
  packages/framework/lib/arguments/string.ts
  packages/framework/lib/arguments/subcommand.ts
  packages/framework/lib/commands/ping.ts
  packages/framework/lib/index.ts
  packages/framework/lib/inhibitors/allowedIn.ts
  packages/framework/lib/inhibitors/cooldown.ts
  packages/framework/lib/monitors/commands.ts
  packages/framework/lib/monitors/messageCollector.ts
  packages/framework/lib/structures/Argument.ts
  packages/framework/lib/structures/Command.ts
  packages/framework/lib/structures/Inhibitor.ts
  packages/framework/lib/structures/Monitor.ts
  packages/framework/lib/utils/walk.ts
  packages/framework/package.json
  packages/framework/test/index.ts
  packages/framework/tsconfig.json
  yarn.lock
Labels: enhancement

#60 Fix/webhooks create params
  packages/guilded.js/lib/managers/global/WebhookManager.ts
  packages/guilded.js/lib/structures/index.ts
  packages/rest/lib/Router.ts
Labels: bug

#66 chore: remove examples
  .github/workflows/ci.yml
  examples/bot-with-command-handler/package.json
  examples/bot-with-command-handler/src/Command.ts
  examples/bot-with-command-handler/src/commands/echo.ts
  examples/bot-with-command-handler/src/commands/ping.ts
  examples/bot-with-command-handler/src/index.ts
  examples/bot-with-command-handler/tsconfig.json
  examples/bot/package.json
  examples/bot/src/index.ts
  examples/bot/tsconfig.json
  examples/rest/package.json
  examples/rest/src/index.ts
  examples/rest/tsconfig.json
  examples/ws/package.json
  examples/ws/src/index.ts
  examples/ws/tsconfig.json
  package.json
Labels: refactor

#67 feat: remove @guildedjs/common
  .changeset/breezy-spoons-joke.md
  .github/workflows/ci.yml
  README.md
  package.json
  packages/common/README.md
  packages/common/__tests__/CacheCollection.test.ts
  packages/common/__tests__/util.test.ts
  packages/common/lib/CacheCollection.ts
  packages/common/lib/UUID.ts
  packages/common/lib/index.ts
  packages/common/lib/util.ts
  packages/common/package.json
  packages/common/tsconfig.json
  packages/guilded.js/README.md
  packages/guilded.js/lib/cache.ts
  packages/guilded.js/lib/constants.ts
  packages/guilded.js/lib/structures/Client.ts
  packages/guilded.js/lib/util.ts
  packages/guilded.js/package.json
  packages/rest/lib/RestManager.ts
  packages/rest/package.json
  packages/webhook-client/lib/WebhookClient.ts
  packages/webhook-client/package.json
  packages/ws/lib/WebSocketManager.ts
  packages/ws/lib/index.ts
  packages/ws/package.json
  pnpm-lock.yaml
  scripts/reset.ts
Labels: refactor

#72 feat: update cached member
  .changeset/late-wasps-destroy.md
  packages/guilded.js/lib/gateway/handler/TeamMemberEventHandler.ts
Labels: bug

#77 feat: get cache before fetching, optional force
  .changeset/three-oranges-call.md
  packages/guilded.js/lib/managers/global/GuildBanManager.ts
  packages/guilded.js/lib/managers/global/MemberManager.ts
  packages/guilded.js/lib/managers/global/MessageManager.ts
  packages/guilded.js/lib/managers/global/WebhookManager.ts
Labels: enhancement

#78 fix: invalid CommandArgument '...strings'
  .changeset/gold-tips-rest.md
  packages/framework/lib/structures/Command.ts
Labels: bug

#80 feat: update ChatMessageDeleted payload
  .changeset/wet-moons-hear.md
  packages/guilded-api-typings/lib/v1/ws/Events.ts
Labels: enhancement

#84 feat: add isSilent to message body
  .changeset/eight-lizards-carry.md
  packages/guilded-api-typings/lib/v1/rest/Message.ts
  packages/guilded-api-typings/lib/v1/structs/Message.ts
  packages/guilded.js/lib/structures/Message.ts
  packages/guilded.js/lib/structures/channels/Channel.ts
  packages/rest/lib/util/Router.ts
Labels: enhancement

#85 feat: user avatar and banner
  .changeset/thin-turtles-sniff.md
  packages/guilded-api-typings/lib/v1/structs/User.ts
  packages/guilded.js/lib/structures/User.ts
Labels: enhancement, guilded.js, guilded-api-typings

#87 fix: allow object for updating message content
  packages/guilded.js/lib/managers/global/MessageManager.ts
  packages/guilded.js/lib/structures/Message.ts
  packages/guilded.js/lib/structures/channels/Channel.ts
Labels: enhancement, guilded.js

#90 fix: constructors should not insert in sets
  packages/gil/lib/structures/Argument.ts
  packages/gil/lib/structures/Command.ts
  packages/gil/lib/structures/Inhibitor.ts
  packages/gil/lib/structures/Monitor.ts
Labels: gil

#89 feat(gil): Implement Tasks Feature
  packages/gil/lib/BotClient.ts
  packages/gil/lib/monitors/commands.ts
  packages/gil/lib/structures/Task.ts
Labels: enhancement, pkg: gil
